[build]
  base = "9.youtube-blog"
  functions = "netlify/functions"

[functions]
  external_node_modules = [
    "express",
    "mongoose",
    "cookie-parser",
    "ejs",
    "multer",
    "jsonwebtoken"
  ]
  node_bundler = "esbuild"
  included_files = [
    "views/**:
    "public/**:
  ]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
